FROM node:26-alpine AS build

WORKDIR /app

RUN apk upgrade --no-cache \
  && npm install --global npm@12.0.2

COPY package.json package-lock.json ./
RUN npm ci

COPY . ./

RUN npm run build

FROM nginxinc/nginx-unprivileged:1.31-alpine AS runtime

USER root
RUN apk upgrade --no-cache
USER 101

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
