images:
  backend:
    repository: ghcr.io/reing01/sicose-backend
    tag: latest
    pullPolicy: Always
  frontend:
    repository: ghcr.io/reing01/sicose-frontend
    tag: latest
    pullPolicy: Always

global:
  namespace: sicose-prod

ingress:
  enabled: true
  className: nginx
  host: sicose-practica.local

cluster:
  physicalNodes: 4
  replicasPerNode: 3

backend:
  replicaCount: null
  scheduling:
    topologySpread:
      enabled: true
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      topologyKey: kubernetes.io/hostname

frontend:
  replicaCount: null
  scheduling:
    topologySpread:
      enabled: true
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      topologyKey: kubernetes.io/hostname

autoscaling:
  enabled: false

pdb:
  enabled: true
  minAvailable: 9

config:
  corsOrigin: http://sicose-practica.local
