apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sicose.fullname" . }}-secret
  namespace: {{ include "sicose.namespace" . }}
  labels:
    {{- include "sicose.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgres:%v/%s" .Values.config.postgresUser .Values.secrets.postgresPassword (include "sicose.fullname" .) .Values.postgres.servicePort .Values.config.postgresDb | quote }}
  DIRECT_URL: {{ printf "postgresql://%s:%s@%s-postgres:%v/%s" .Values.config.postgresUser .Values.secrets.postgresPassword (include "sicose.fullname" .) .Values.postgres.servicePort .Values.config.postgresDb | quote }}
  REDIS_URL: {{ printf "redis://%s-redis:%v" (include "sicose.fullname" .) .Values.redis.servicePort | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  SUPABASE_URL: {{ .Values.secrets.supabaseUrl | quote }}
  SUPABASE_SERVICE_KEY: {{ .Values.secrets.supabaseServiceKey | quote }}
